-- 코드를 작성해주세요

SELECT ID FROM ECOLI_DATA
WHERE PARENT_ID IN (
    SELECT d1.ID FROM ECOLI_DATA d1
    WHERE d1.PARENT_ID IN (
        SELECT d2.ID FROM ECOLI_DATA d2
        WHERE d2.PARENT_ID IS NULL
    )
)