SELECT 
    ROUTE,
    CONCAT(
        TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM (SUM(D_BETWEEN_DIST)+0))),
        'km'
    ) AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;