WITH yearly_max AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT
    ym.YEAR,
    (ym.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID AS ID
FROM ECOLI_DATA e JOIN yearly_max ym ON ym.YEAR = YEAR(e.DIFFERENTIATION_DATE)
ORDER BY ym.year, YEAR_DEV