-- 코드를 작성해주세요

WITH MAX_LENGTH AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT fi.ID, fni.FISH_NAME, ml.LENGTH
FROM MAX_LENGTH ml JOIN FISH_INFO fi ON ml.FISH_TYPE = fi.FISH_TYPE AND ml.LENGTH = fi.LENGTH
JOIN FISH_NAME_INFO fni ON ml.FISH_TYPE = fni.FISH_TYPE
ORDEr BY fi.ID ASC

