-- 코드를 작성해주세요
WITH FISH_AVG AS (
    SELECT 
        FISH_TYPE,
        MAX(COALESCE(LENGTH, 10)) AS MAX_LENGTH,
        AVG(COALESCE(LENGTH, 10)) AS AVG_LENGTH,
        COUNT(*) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT
    fa.FISH_COUNT,
    fa.MAX_LENGTH,
    fa.FISH_TYPE
FROM FISH_AVG fa
WHERE fa.AVG_LENGTH >= 33
ORDER BY fa.FISH_TYPE
    